INSERT IGNORE INTO `m4j_songs` (`id`, `event_id`, `title`, `artist`, `genre`, `lyrics`) VALUES
(1, 2, 'Back in Black', 'AC/DC', 'Hard Rock', NULL),
(2, 2, 'Highway to Hell', 'AC/DC', 'Hard Rock', NULL),
(3, 2, 'Thunderstruck', 'AC/DC', 'Hard Rock', NULL),
(4, 2, 'Paranoid', 'Black Sabbath', 'Heavy Metal', NULL),
(5, 2, 'War Pigs', 'Black Sabbath', 'Heavy Metal', NULL),
(6, 2, 'Iron Man', 'Black Sabbath', 'Heavy Metal', NULL),
(7, 2, 'Changes', 'Black Sabbath', 'Heavy Metal', NULL),
(9, 2, 'Sabbath Bloody Sabbath', 'Black Sabbath', 'Heavy Metal', NULL),
(10, 2, 'N.I.B.', 'Black Sabbath', 'Heavy Metal', NULL),
(11, 2, 'Children of the Grave', 'Black Sabbath', 'Heavy Metal', NULL),
(12, 2, 'The Wizard', 'Black Sabbath', 'Heavy Metal', NULL),
(14, 2, 'Stillborn', 'Black Label Society', 'Heavy Metal', NULL),
(15, 2, 'Sweet Child O'' Mine', 'Guns N'' Roses', 'Hard Rock', NULL),
(16, 2, 'Welcome to the Jungle', 'Guns N'' Roses', 'Hard Rock', NULL),
(17, 2, 'Paradise City', 'Guns N'' Roses', 'Hard Rock', NULL),
(18, 2, 'The Trooper', 'Iron Maiden', 'Heavy Metal', NULL),
(19, 2, 'Run to the Hills', 'Iron Maiden', 'Heavy Metal', NULL),
(20, 2, 'Fear of the Dark', 'Iron Maiden', 'Heavy Metal', NULL),
(21, 2, 'Aces High', 'Iron Maiden', 'Heavy Metal', NULL),
(22, 2, '2 Minutes to Midnight', 'Iron Maiden', 'Heavy Metal', NULL),
(23, 2, 'Revelations', 'Iron Maiden', 'Heavy Metal', NULL),
(24, 2, 'Flight of Icarus', 'Iron Maiden', 'Heavy Metal', NULL),
(25, 2, 'Rime of the Ancient Mariner', 'Iron Maiden', 'Heavy Metal', NULL),
(26, 2, 'Powerslave', 'Iron Maiden', 'Heavy Metal', NULL),
(27, 2, 'The Number of the Beast', 'Iron Maiden', 'Heavy Metal', NULL),
(28, 2, 'Hallowed Be Thy Name', 'Iron Maiden', 'Heavy Metal', NULL),
(29, 2, 'Iron Maiden', 'Iron Maiden', 'Heavy Metal', NULL),
(30, 2, 'Running Free', 'Iron Maiden', 'Heavy Metal', NULL),
(31, 2, 'Wrathchild', 'Iron Maiden', 'Heavy Metal', NULL),
(32, 2, '22 Acacia Avenue', 'Iron Maiden', 'Heavy Metal', NULL),
(33, 2, 'Children of the Damned', 'Iron Maiden', 'Heavy Metal', NULL),
(34, 2, 'Die With Your Boots On', 'Iron Maiden', 'Heavy Metal', NULL),
(35, 2, 'Phantom of the Opera', 'Iron Maiden', 'Heavy Metal', NULL),
(36, 2, 'Flash of the Blade', 'Iron Maiden', 'Heavy Metal', NULL),
(37, 2, 'Moonchild', 'Iron Maiden', 'Heavy Metal', NULL),
(38, 2, 'Breaking the Law', 'Judas Priest', 'Heavy Metal', NULL),
(39, 2, 'Painkiller', 'Judas Priest', 'Heavy Metal', NULL),
(40, 2, 'You''ve Got Another Thing Coming', 'Judas Priest', 'Heavy Metal', NULL),
(43, 2, 'Electric Eye', 'Judas Priest', 'Heavy Metal', NULL),
(45, 2, 'Night Crawler', 'Judas Priest', 'Heavy Metal', NULL),
(49, 2, 'The Hellion', 'Judas Priest', 'Heavy Metal', NULL),
(50, 2, 'A Touch of Evil', 'Judas Priest', 'Heavy Metal', NULL),
(52, 2, 'Grinder', 'Judas Priest', 'Heavy Metal', NULL),
(53, 2, 'Hell Bent for Leather', 'Judas Priest', 'Heavy Metal', NULL),
(56, 2, 'Desert Plains', 'Judas Priest', 'Heavy Metal', NULL),
(57, 2, 'Symphony of Destruction', 'Megadeth', 'Thrash Metal', NULL),
(58, 2, 'Holy Wars... The Punishment Due', 'Megadeth', 'Thrash Metal', NULL),
(59, 2, 'Hangar 18', 'Megadeth', 'Thrash Metal', NULL),
(60, 2, 'Master of Puppets', 'Metallica', 'Thrash Metal', NULL),
(61, 2, 'Enter Sandman', 'Metallica', 'Heavy Metal', NULL),
(62, 2, 'For Whom the Bell Tolls', 'Metallica', 'Thrash Metal', NULL),
(63, 2, 'Fuel', 'Metallica', 'Heavy Metal', NULL),
(64, 2, 'Whiplash', 'Metallica', 'Thrash Metal', NULL),
(65, 2, 'Welcome Home', 'Metallica', 'Heavy Metal', NULL),
(66, 2, 'Fade to Black', 'Metallica', 'Thrash Metal', NULL),
(67, 2, 'Until It Sleeps', 'Metallica', 'Heavy Metal', NULL),
(68, 2, 'Turn the Page', 'Metallica', 'Heavy Metal', NULL),
(69, 2, 'The Unforgiven', 'Metallica', 'Heavy Metal', NULL),
(70, 2, 'Seek & Destroy', 'Metallica', 'Thrash Metal', NULL),
(71, 2, 'Wherever I May Roam', 'Metallica', 'Heavy Metal', NULL),
(72, 2, 'One', 'Metallica', 'Thrash Metal', NULL),
(73, 2, 'Nothing Else Matters', 'Metallica', 'Heavy Metal', NULL),
(74, 2, 'Whiskey in the Jar', 'Metallica', 'Hard Rock', NULL),
(75, 2, 'Sad But True', 'Metallica', 'Heavy Metal', NULL),
(76, 2, 'Pulling Teeth', 'Metallica', 'Heavy Metal', NULL),
(77, 2, 'Am I Evil?', 'Metallica', 'Heavy Metal', NULL),
(78, 2, 'Creeping Death', 'Metallica', 'Thrash Metal', NULL),
(79, 2, 'Ace of Spades', 'Motörhead', 'Heavy Metal', NULL),
(80, 2, 'Crazy Train', 'Ozzy Osbourne', 'Heavy Metal', NULL),
(81, 2, 'Mr. Crowley', 'Ozzy Osbourne', 'Heavy Metal', NULL),
(82, 2, 'Bark at the Moon', 'Ozzy Osbourne', 'Heavy Metal', NULL),
(83, 2, 'Mama I''m Coming Home', 'Ozzy Osbourne', 'Heavy Metal', NULL),
(84, 2, 'No More Tears', 'Ozzy Osbourne', 'Heavy Metal', NULL),
(85, 2, 'I Don''t Wanna Stop', 'Ozzy Osbourne', 'Heavy Metal', NULL),
(86, 2, 'I Don''t Know', 'Ozzy Osbourne', 'Heavy Metal', NULL),
(87, 2, 'Shot in the Dark', 'Ozzy Osbourne', 'Heavy Metal', NULL),
(88, 2, 'Dreamer', 'Ozzy Osbourne', 'Heavy Metal', NULL),
(89, 2, 'Hellraiser', 'Ozzy Osbourne', 'Heavy Metal', NULL),
(91, 2, 'Suicide Solution', 'Ozzy Osbourne', 'Heavy Metal', NULL),
(92, 2, 'Walk', 'Pantera', 'Groove Metal', NULL),
(93, 2, 'Cowboys from Hell', 'Pantera', 'Groove Metal', NULL),
(94, 2, 'This Love', 'Pantera', 'Groove Metal', NULL),
(95, 2, 'Fucking Hostile', 'Pantera', 'Groove Metal', NULL),
(96, 2, 'Killing in the Name', 'Rage Against the Machine', 'Alternative Metal', NULL),
(97, 2, 'Bulls on Parade', 'Rage Against the Machine', 'Alternative Metal', NULL),
(98, 2, 'Roots Bloody Roots', 'Sepultura', 'Groove Metal', NULL),
(99, 2, 'Refuse/Resist', 'Sepultura', 'Groove Metal', NULL),
(102, 2, 'Inner Self', 'Sepultura', 'Groove Metal', NULL),
(104, 2, 'Territory', 'Sepultura', 'Groove Metal', NULL),
(105, 2, 'Arise', 'Sepultura', 'Groove Metal', NULL),
(106, 2, 'Symptom of the Universe', 'Black Sabbath', 'Groove Metal', NULL),
(108, 2, 'Slave New World', 'Sepultura', 'Groove Metal', NULL),
(109, 2, 'Orgasmatron', 'Sepultura', 'Groove Metal', NULL),
(112, 2, 'Propaganda', 'Sepultura', 'Groove Metal', NULL),
(113, 2, 'Desperate Cry', 'Sepultura', 'Groove Metal', NULL),
(114, 2, 'Beneath the Remains', 'Sepultura', 'Groove Metal', NULL),
(115, 2, 'Troops of Doom', 'Sepultura', 'Groove Metal', NULL),
(116, 2, 'Mouth for War', 'Pantera', 'Groove Metal', NULL),
(117, 2, 'South of Heaven', 'Slayer', 'Thrash Metal', NULL),
(118, 2, 'Mandatory Suicide', 'Slayer', 'Thrash Metal', NULL),
(119, 2, 'Seasons in the Abyss', 'Slayer', 'Thrash Metal', NULL),
(120, 2, 'Angel of Death', 'Slayer', 'Thrash Metal', NULL),
(121, 2, 'Chop Suey!', 'System of a Down', 'Alternative Metal', NULL),
(122, 2, 'Toxicity', 'System of a Down', 'Alternative Metal', NULL);
